---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - catalog.bookstore.io
  resources:
  - authors
  - books
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.bookstore.io
  resources:
  - authors/finalizers
  - books/finalizers
  verbs:
  - update
- apiGroups:
  - catalog.bookstore.io
  resources:
  - authors/status
  - books/status
  verbs:
  - get
  - patch
  - update
